# cargo-about configuration for the third-party licence inventory shipped with a release
# (`cargo about generate about.hbs > THIRD_PARTY_LICENSES.html`). Keep in sync with the
# allow-list in deny.toml.
accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "0BSD",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "MulanPSL-2.0",
]
targets = [
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
